"""
Django settings for GIADUNGPLUS project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import sys

# Set environment variable for UTF-8 encoding to handle Vietnamese Unicode characters
os.environ.setdefault('PYTHONIOENCODING', 'utf-8')

# Setup Unicode-safe streams early (before logging is configured)
try:
    from GIADUNGPLUS.logging_handlers import setup_unicode_safe_streams
    setup_unicode_safe_streams()
except Exception:
    # If setup fails, continue without it
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Thêm PostgreSQL bin vào PATH để Django có thể tìm thấy psql (cho dbshell command)
# Tự động tìm các đường dẫn PostgreSQL phổ biến trên Windows (ưu tiên version 18)
pg_bin_paths = [
    r"C:\Program Files\PostgreSQL\18\bin",
    r"C:\Program Files\PostgreSQL\15\bin",
    r"C:\Program Files\PostgreSQL\14\bin",
    r"C:\Program Files\PostgreSQL\13\bin",
]
current_path = os.environ.get('PATH', '')
for pg_bin in pg_bin_paths:
    if os.path.exists(pg_bin) and pg_bin not in current_path:
        os.environ['PATH'] = pg_bin + os.pathsep + os.environ.get('PATH', '')
        break


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ij_x(m14of25wzvf(upyjsrdu+%@d_9hjx29%n8lqr3ce#j-xf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["giadungplus.io.vn", "103.110.85.223",'*']
CSRF_TRUSTED_ORIGINS = ["https://giadungplus.io.vn"]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    "kho",
    "cskh",
    "marketing",
    "service",
    "core",
    "orders",
    "products",
    "customers",
    "settings",
    "chamcong",
    'rest_framework',
    'sslserver',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'GIADUNGPLUS.middleware.port_redirect.PortRedirectMiddleware',
    'core.middleware.selenium_login_middleware.SeleniumLoginMiddleware',  # Catch Selenium login exceptions
    'kho.middleware.KhoSwitcherMiddleware',
]

INSTALLED_APPS += ["whitenoise.runserver_nostatic"]
MIDDLEWARE = ["whitenoise.middleware.WhiteNoiseMiddleware", *MIDDLEWARE]
ROOT_URLCONF = 'GIADUNGPLUS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.product_counts',
                'chamcong.context_processors.attendance_reminder',
            ],
        },
    },
]

WSGI_APPLICATION = 'GIADUNGPLUS.wsgi.application'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'my_session'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Cấu hình Django để sử dụng HTTPS
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False        # tránh vòng lặp redirect kỳ cục khi đã HTTPS
SESSION_COOKIE_SECURE = True       # dev HTTPS: có thể bật
CSRF_COOKIE_SECURE = True          # dev HTTPS: có thể bật
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# PostgreSQL configuration (học từ settings_production.py)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'giadungplus_db',
        'USER': 'giadungplus',
        'PASSWORD': '123122aC@',
        'HOST': os.environ.get('DB_HOST', 'localhost'),  # Mặc định localhost cho môi trường local/development
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}
# Override với biến môi trường nếu có (cho phép linh hoạt)
if os.environ.get('DB_NAME'):
    DATABASES['default']['NAME'] = os.environ.get('DB_NAME')
if os.environ.get('DB_USER'):
    DATABASES['default']['USER'] = os.environ.get('DB_USER')
if os.environ.get('DB_PASSWORD'):
    DATABASES['default']['PASSWORD'] = os.environ.get('DB_PASSWORD')

# Cache configuration (for Selenium lock mechanism)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'sapo-selenium-lock',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'assets'),
)


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"   # Dashboard homepage sau khi login
LOGOUT_REDIRECT_URL = "/login/"  # Redirect về trang login sau khi logout

import sys

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'GIADUNGPLUS.logging_handlers.SafeUnicodeStreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'errors': 'replace',
        },
        'console_safe': {
            'level': 'DEBUG',
            'class': 'GIADUNGPLUS.logging_handlers.SafeUnicodeStreamHandler',
            'stream': sys.stderr,
            'formatter': 'simple',
            'encoding': 'utf-8',
            'errors': 'replace',
        },
    },
    'loggers': {
        # Django framework - đặt INFO để ẩn các log "200 OK" liên tục
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django request/response - đặt WARNING để chỉ thấy warnings và errors
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django server - đặt INFO để giảm log
        'django.server': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # SQL queries - đặt INFO để giảm SQL debug logs
        'django.db.backends': {
            'handlers': ['file', 'console_safe'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends.utils': {
            'handlers': ['file', 'console_safe'],
            'level': 'INFO',
            'propagate': False,
        },
        # App của bạn - giữ DEBUG để thấy log do bạn tự viết
        'cskh': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'kho': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'orders': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'products': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'marketing': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'customers': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'settings': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'service': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
}