# Generated by Django 5.0 on 2025-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SapoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('headers', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
