# Generated by Django 5.0 on 2025-12-03 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('android_web', 'Android Web (Chrome)'), ('ios_web', 'iOS Web (Safari)'), ('unknown', 'Unknown Web')], default='unknown', help_text='Loại thiết bị: android_web, ios_web, unknown', max_length=32)),
                ('endpoint', models.TextField(blank=True, null=True)),
                ('p256dh', models.TextField(blank=True, null=True)),
                ('auth', models.TextField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webpush_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Push Subscription',
                'verbose_name_plural': 'Web Push Subscriptions',
                'indexes': [models.Index(fields=['endpoint'], name='core_webpus_endpoin_d035b3_idx'), models.Index(fields=['fcm_token'], name='core_webpus_fcm_tok_e026d9_idx'), models.Index(fields=['device_type'], name='core_webpus_device__2c5aff_idx')],
            },
        ),
    ]
