# Generated by Django 5.0 on 2025-12-04 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_webpushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề thông báo', max_length=200)),
                ('body', models.TextField(help_text='Nội dung thông báo')),
                ('link', models.CharField(blank=True, help_text='URL khi click vào thông báo', max_length=500, null=True)),
                ('action', models.CharField(choices=[('show_popup', 'Hiển thị popup'), ('play_sound', 'Phát âm thanh'), ('badge_update', 'Cập nhật badge'), ('boss_popup', 'Thông báo của sếp')], default='show_popup', help_text='Loại hành động: show_popup, play_sound, badge_update, boss_popup', max_length=50)),
                ('sound', models.CharField(blank=True, help_text='Link sound ở /static/ (nếu có)', max_length=500, null=True)),
                ('count', models.IntegerField(blank=True, help_text='Số lượng cho badge_update', null=True)),
                ('collapse_id', models.CharField(blank=True, db_index=True, help_text='ID/tag để đè notify cũ bằng notify mới', max_length=100, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, help_text='Tag phân loại thông báo', max_length=100, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, help_text='Thời gian hẹn gửi (nếu có, null = gửi ngay)', null=True)),
                ('event_type', models.CharField(blank=True, db_index=True, help_text='Loại event từ business layer (ví dụ: ticket_created, order_updated)', max_length=100, null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Dữ liệu context từ business layer (JSON)')),
                ('status', models.CharField(choices=[('pending', 'Chờ gửi'), ('sent', 'Đã gửi'), ('failed', 'Gửi thất bại'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_notifi_status_58cb4f_idx'), models.Index(fields=['collapse_id'], name='core_notifi_collaps_5e917b_idx'), models.Index(fields=['tag'], name='core_notifi_tag_8a94b9_idx'), models.Index(fields=['event_type'], name='core_notifi_event_t_79fcf7_idx'), models.Index(fields=['scheduled_time', 'status'], name='core_notifi_schedul_8ac90c_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web_push', 'Web Push'), ('in_app', 'In-app'), ('email', 'Email')], db_index=True, default='in_app', help_text='Kênh gửi: web_push, in_app, email', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ gửi'), ('sent', 'Đã gửi'), ('failed', 'Gửi thất bại')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('delivery_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata về delivery (subscription_id, response, etc.)')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(help_text='Thông báo được gửi', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.notification')),
                ('user', models.ForeignKey(help_text='User nhận thông báo', on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_f1f5cc_idx'), models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_128b60_idx'), models.Index(fields=['notification', 'channel'], name='core_notifi_notific_66dd22_idx'), models.Index(fields=['status'], name='core_notifi_status_44cd97_idx')],
                'unique_together': {('notification', 'user', 'channel')},
            },
        ),
    ]
