# Generated by Django 5.0 on 2025-12-16 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('CSKH', 'CSKH'), ('KHO', 'Kho hàng'), ('MARKETING', 'Marketing'), ('ADMIN', 'Admin / Quản trị')], help_text='Bộ phận làm việc (map với last_name của user)', max_length=50)),
                ('latitude', models.FloatField(help_text='Vĩ độ (GPS)')),
                ('longitude', models.FloatField(help_text='Kinh độ (GPS)')),
                ('radius_m', models.PositiveIntegerField(default=150, help_text='Bán kính cho phép tính từ điểm chuẩn (mét)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Địa điểm chấm công',
                'verbose_name_plural': 'Địa điểm chấm công',
            },
        ),
        migrations.CreateModel(
            name='WorkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSKH', 'CSKH'), ('KHO', 'Kho hàng'), ('MARKETING', 'Marketing'), ('ADMIN', 'Admin / Quản trị')], help_text='Bộ phận làm việc (last_name của user)', max_length=50)),
                ('group_name', models.CharField(help_text='Tên group quyền (VD: WarehouseManager, CSKHStaff, MarketingManager...)', max_length=100)),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu chuẩn (VD: 08:30)')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc chuẩn (VD: 17:30)')),
                ('allow_overtime', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quy định giờ làm',
                'verbose_name_plural': 'Quy định giờ làm',
                'unique_together': {('department', 'group_name', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text='Bộ phận làm việc tại thời điểm chấm công (last_name)', max_length=50)),
                ('group_name', models.CharField(help_text='Chức vụ / group tại thời điểm chấm công', max_length=100)),
                ('work_date', models.DateField(help_text='Ngày làm việc (theo GMT+7)')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.FloatField(blank=True, null=True)),
                ('check_in_longitude', models.FloatField(blank=True, null=True)),
                ('check_in_address', models.CharField(blank=True, help_text='Địa chỉ hiển thị (optional)', max_length=255, null=True)),
                ('check_in_location_valid', models.BooleanField(default=False, help_text='Vị trí check-in có hợp lệ hay không')),
                ('check_in_photo', models.ImageField(blank=True, help_text='Ảnh selfie khi check-in', null=True, upload_to='attendance/selfies/')),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.FloatField(blank=True, null=True)),
                ('check_out_longitude', models.FloatField(blank=True, null=True)),
                ('check_out_address', models.CharField(blank=True, help_text='Địa chỉ hiển thị (optional)', max_length=255, null=True)),
                ('check_out_location_valid', models.BooleanField(default=False, help_text='Vị trí check-out có hợp lệ hay không')),
                ('check_out_photo', models.ImageField(blank=True, help_text='Ảnh selfie khi check-out (nếu cần)', null=True, upload_to='attendance/selfies/')),
                ('total_minutes', models.PositiveIntegerField(default=0, help_text='Tổng giờ làm (phút)')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, help_text='Số phút tăng ca (nếu có)')),
                ('approval_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'indexes': [models.Index(fields=['work_date', 'department'], name='chamcong_at_work_da_106af5_idx'), models.Index(fields=['user', 'work_date'], name='chamcong_at_user_id_3de35c_idx')],
            },
        ),
    ]
