# Generated by Django 5.0 on 2025-12-16 11:24

import chamcong.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamcong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều'), ('evening', 'Ca tối')], help_text='Ca làm: sáng / chiều / tối', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_photo',
            field=models.ImageField(blank=True, help_text='Ảnh selfie khi check-in (assets/nhanvien/chamcong)', null=True, storage=chamcong.storage.ChamCongPhotoStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_out_photo',
            field=models.ImageField(blank=True, help_text='Ảnh selfie khi check-out (nếu cần, assets/nhanvien/chamcong)', null=True, storage=chamcong.storage.ChamCongPhotoStorage(), upload_to=''),
        ),
    ]
