# Generated by Django 5.0 on 2025-12-16 15:58

import chamcong.models
import chamcong.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamcong', '0002_attendancerecord_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_photo',
            field=models.ImageField(blank=True, help_text='Ảnh selfie khi check-in (assets/nhanvien/chamcong)', null=True, storage=chamcong.storage.ChamCongPhotoStorage(), upload_to=chamcong.models.attendance_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_out_photo',
            field=models.ImageField(blank=True, help_text='Ảnh selfie khi check-out (nếu cần, assets/nhanvien/chamcong)', null=True, storage=chamcong.storage.ChamCongPhotoStorage(), upload_to=chamcong.models.attendance_photo_upload_to),
        ),
    ]
