# Generated by Django 5.0 on 2025-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamcong', '0003_alter_attendancerecord_check_in_photo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workrule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='worklocation',
            name='department',
        ),
        migrations.AddField(
            model_name='workrule',
            name='shift',
            field=models.CharField(choices=[('morning', 'Ca sáng'), ('evening', 'Ca tối')], default='morning', help_text='Ca làm việc: sáng hoặc tối', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='workrule',
            unique_together={('department', 'group_name', 'shift', 'is_active')},
        ),
    ]
