# Generated by Django 5.0 on 2025-12-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamcong', '0004_alter_workrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrule',
            name='department',
            field=models.CharField(choices=[('CSKH', 'CSKH'), ('KHO_HCM', 'Kho hàng HCM'), ('KHO_HN', 'Kho hàng HN'), ('MARKETING', 'Marketing'), ('ADMIN', 'Admin / Quản trị')], help_text='Bộ phận làm việc (last_name của user)', max_length=50),
        ),
    ]
