# Generated by Django 5.0 on 2025-12-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamcong', '0005_alter_workrule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrule',
            name='end_time',
            field=models.TimeField(help_text='Giờ kết thúc chuẩn (24h, VD: 17:30)'),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='shift',
            field=models.CharField(choices=[('morning', 'Ca sáng'), ('afternoon', 'Ca chiều'), ('evening', 'Ca tối')], default='morning', help_text='Ca làm việc: sáng / chiều / tối', max_length=20),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='start_time',
            field=models.TimeField(help_text='Giờ bắt đầu chuẩn (24h, VD: 08:30)'),
        ),
    ]
