# Generated by Django 5.0 on 2025-12-09 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('page_url', models.TextField(help_text='URL của trang web chứa media')),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('media_url', models.TextField(help_text='URL của file video/audio (.mp3, .mp4, .mov)')),
                ('file_extension', models.CharField(help_text='mp4, mp3, mov', max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_type', models.CharField(choices=[('video_tag', 'Video Tag'), ('audio_tag', 'Audio Tag'), ('network_request', 'Network Request')], default='video_tag', help_text='Nguồn phát hiện media', max_length=50)),
                ('user_name', models.CharField(db_index=True, help_text='Username được setup từ extension, trùng với username trên admin', max_length=150)),
                ('tab_id', models.IntegerField(blank=True, help_text='Chrome tab ID', null=True)),
                ('thumbnail_url', models.TextField(blank=True, help_text='URL ảnh đại diện video', null=True)),
            ],
            options={
                'verbose_name': 'Media Track',
                'verbose_name_plural': 'Media Tracks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_name', '-created_at'], name='marketing_m_user_na_a0396d_idx'), models.Index(fields=['file_extension'], name='marketing_m_file_ex_123039_idx')],
            },
        ),
    ]
