# Generated by Django 5.0 on 2025-11-24 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chương trình')),
                ('scope', models.CharField(choices=[('order', 'Theo đơn hàng'), ('line', 'Theo sản phẩm')], max_length=20, verbose_name='Phạm vi áp dụng')),
                ('shop_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã shop (optional)')),
                ('min_order_total', models.BigIntegerField(blank=True, null=True, verbose_name='Giá trị đơn tối thiểu (đồng)')),
                ('max_order_total', models.BigIntegerField(blank=True, null=True, verbose_name='Giá trị đơn tối đa (đồng)')),
                ('required_variant_id', models.BigIntegerField(blank=True, null=True, verbose_name='Variant ID sản phẩm yêu cầu')),
                ('required_min_qty', models.IntegerField(blank=True, null=True, verbose_name='Số lượng tối thiểu')),
                ('required_max_qty', models.IntegerField(blank=True, null=True, verbose_name='Số lượng tối đa')),
                ('priority', models.IntegerField(default=0, verbose_name='Độ ưu tiên (số càng cao càng ưu tiên)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('stop_further', models.BooleanField(default=False, verbose_name='Dừng xét rule khác sau khi áp dụng')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Rule',
                'verbose_name_plural': 'Gift Rules',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', '-priority'], name='settings_gi_is_acti_f570f1_idx'), models.Index(fields=['shop_code'], name='settings_gi_shop_co_87a6ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftRuleGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_variant_id', models.BigIntegerField(verbose_name='Variant ID của quà tặng')),
                ('gift_qty', models.IntegerField(default=1, verbose_name='Số lượng quà tặng')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='settings.giftrule', verbose_name='Gift Rule')),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
            },
        ),
    ]
