# Generated by Django 5.0 on 2025-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftrule',
            name='required_variant_id',
        ),
        migrations.AddField(
            model_name='giftrule',
            name='required_variant_ids',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách IDs của variants (JSON array)', verbose_name='Variant IDs sản phẩm yêu cầu'),
        ),
        migrations.AlterField(
            model_name='giftrule',
            name='max_order_total',
            field=models.BigIntegerField(blank=True, help_text="Giá trị đơn hàng tối đa (VNĐ) khi scope='order'", null=True, verbose_name='Giá trị đơn tối đa (đồng)'),
        ),
        migrations.AlterField(
            model_name='giftrule',
            name='min_order_total',
            field=models.BigIntegerField(blank=True, help_text="Giá trị đơn hàng tối thiểu (VNĐ) khi scope='order'", null=True, verbose_name='Giá trị đơn tối thiểu (đồng)'),
        ),
        migrations.AlterField(
            model_name='giftrule',
            name='required_max_qty',
            field=models.IntegerField(blank=True, help_text="Số lượng sản phẩm tối đa khi scope='line'", null=True, verbose_name='Số lượng tối đa'),
        ),
        migrations.AlterField(
            model_name='giftrule',
            name='required_min_qty',
            field=models.IntegerField(blank=True, help_text="Số lượng sản phẩm tối thiểu khi scope='line'", null=True, verbose_name='Số lượng tối thiểu'),
        ),
    ]
