# Generated by Django 5.0 on 2025-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_change_variant_id_to_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftrulegift',
            name='match_quantity',
            field=models.BooleanField(default=False, help_text='Nếu True, số lượng quà = số lượng sản phẩm mua. Nếu False, số lượng quà cố định.', verbose_name='Tặng theo số lượng mua (1:1)'),
        ),
    ]
