# Generated by Django 5.0 on 2025-12-09 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_add_match_quantity_to_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.CharField(help_text='Ví dụ: Đang đẩy mạnh, Duy trì ổn định, Xả kho gấp...', max_length=255, unique=True, verbose_name='Tên tag (tiếng Việt)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variant Tag',
                'verbose_name_plural': 'Variant Tags',
                'ordering': ['tags_name'],
            },
        ),
    ]
