# Generated by Django 5.0 on 2025-12-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_varianttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttag',
            name='color',
            field=models.CharField(default='blue', help_text='Màu sắc để hiển thị tag (blue, green, red, yellow, orange, purple, gray, pink)', max_length=50, verbose_name='Màu sắc'),
        ),
    ]
