# Generated by Django 5.0 on 2025-11-26 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('order_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('shop', models.CharField(blank=True, max_length=100)),
                ('variants_issue', models.JSONField(blank=True, default=list)),
                ('ticket_type', models.CharField(blank=True, choices=[('bad_review', 'Đánh giá xấu'), ('return_exchange', 'Đổi trả'), ('warranty', 'Bảo hành'), ('damaged', 'Hỏng vỡ'), ('customer_request', 'Khách yêu cầu'), ('wrong_delivery', 'Giao sai, thiếu'), ('wrong_order', 'Lên đơn sai')], max_length=50)),
                ('ticket_status', models.CharField(choices=[('new', 'Mới'), ('processing', 'Đang xử lý'), ('waiting_customer', 'Chờ khách'), ('waiting_warehouse', 'Chờ kho'), ('resolved', 'Đã xử lý'), ('closed', 'Đóng')], default='new', max_length=50)),
                ('source_ticket', models.CharField(choices=[('cskh_created', 'CSKH tạo'), ('customer_request', 'Khách request'), ('automation', 'Hệ thống tự tạo')], default='cskh_created', max_length=50)),
                ('depart', models.CharField(choices=[('cskh', 'CSKH'), ('warehouse', 'Kho')], default='cskh', max_length=50)),
                ('source_reason', models.CharField(blank=True, max_length=100)),
                ('reason_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cskh_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cskh_tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='cskh.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reason', models.CharField(max_length=100)),
                ('reason_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source_reason', 'reason_type'],
                'unique_together': {('source_reason', 'reason_type')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_status', '-created_at'], name='cskh_ticket_ticket__1e362f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order_id'], name='cskh_ticket_order_i_2d6b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order_code'], name='cskh_ticket_order_c_caeeee_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reference_number'], name='cskh_ticket_referen_ed0549_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='cskh_ticket_ticket__7f5b09_idx'),
        ),
    ]
