# Generated by Django 5.0 on 2025-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
