# Generated by Django 5.0 on 2025-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0002_ticket_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.BigIntegerField(db_index=True, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
