# Generated by Django 5.0 on 2025-11-26 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0006_ticket_process_order_code_ticket_process_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='cskh.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'user'], name='cskh_ticket_ticket__b8f963_idx'), models.Index(fields=['user', '-last_viewed_at'], name='cskh_ticket_user_id_b1bf7a_idx')],
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
