# Generated by Django 5.0 on 2025-11-26 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0007_ticketview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='responsible_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bộ phận chịu trách nhiệm'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsible_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú trách nhiệm'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cskh_tickets_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Người chịu trách nhiệm'),
        ),
    ]
