# Generated by Django 5.0 on 2025-11-26 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0008_ticket_responsible_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_depart', models.CharField(choices=[('cskh', 'CSKH'), ('warehouse', 'Kho')], max_length=50)),
                ('to_depart', models.CharField(choices=[('cskh', 'CSKH'), ('warehouse', 'Kho')], max_length=50)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cskh.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
