# Generated by Django 5.0 on 2025-12-01 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0010_ticket_sugget_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.BigIntegerField(db_index=True, unique=True)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('connection_id', models.IntegerField(db_index=True)),
                ('cmt_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('item_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_image', models.URLField(blank=True, max_length=500)),
                ('channel_order_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('buyer_user_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('rating', models.IntegerField(db_index=True)),
                ('comment', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status_reply', models.CharField(blank=True, max_length=50, null=True)),
                ('reply', models.TextField(blank=True)),
                ('reply_time', models.BigIntegerField(blank=True, null=True)),
                ('user_reply', models.CharField(blank=True, max_length=200)),
                ('reply_type', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sapo_customer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sapo_order_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sapo_product_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sapo_variant_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ai_processed_name', models.BooleanField(default=False)),
                ('ai_processed_gender', models.BooleanField(default=False)),
                ('ai_suggested_reply', models.TextField(blank=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cskh_feedbacks', to='cskh.ticket')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('rating_before', models.IntegerField(blank=True, null=True)),
                ('rating_after', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cskh.feedback')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['rating', '-create_time'], name='cskh_feedba_rating_ad2b79_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['connection_id', '-create_time'], name='cskh_feedba_connect_a71d36_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status_reply', '-create_time'], name='cskh_feedba_status__f04a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['buyer_user_name'], name='cskh_feedba_buyer_u_370968_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['channel_order_number'], name='cskh_feedba_channel_1c3e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklog',
            index=models.Index(fields=['feedback', '-created_at'], name='cskh_feedba_feedbac_06ddaf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklog',
            index=models.Index(fields=['user', '-created_at'], name='cskh_feedba_user_id_ee5711_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklog',
            index=models.Index(fields=['action_type', '-created_at'], name='cskh_feedba_action__93eb31_idx'),
        ),
    ]
