# Generated by Django 5.0 on 2025-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0011_ticket_rating_feedback_feedbacklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
