# Generated by Django 5.0 on 2025-12-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0012_fix_feedback_reply_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_reply',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
