# Generated by Django 5.0 on 2025-12-02 06:51

import django.utils.timezone
from django.db import migrations, models
from django.core.exceptions import FieldError


def ensure_columns_exist(apps, schema_editor):
    """Ensure all required columns exist, create them if not"""
    # Chỉ chạy logic PRAGMA cho SQLite (dev/local).
    # Trên PostgreSQL/MySQL, các cột đã được tạo bởi migration 0014,
    # nên bỏ qua để tránh lỗi cú pháp.
    if schema_editor.connection.vendor != "sqlite":
        return

    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if columns exist
        cursor.execute("PRAGMA table_info(cskh_feedback)")
        columns = {row[1] for row in cursor.fetchall()}
        
        # Fields that might have been added by migration 0014
        fields_to_check = {
            'comment_id': 'bigint NULL',
            'can_follow_up': 'bool NULL',
            'ctime': 'bigint NULL',
            'follow_up': 'text NULL',
            'is_hidden': 'bool NOT NULL DEFAULT 0',
            'low_rating_reasons': 'text NOT NULL DEFAULT \'[]\'',
            'model_id': 'bigint NULL',
            'model_name': 'varchar(500) NOT NULL DEFAULT ""',
            'mtime': 'bigint NULL',
            'order_id': 'bigint NULL',
            'product_cover': 'varchar(200) NOT NULL DEFAULT ""',
            'product_id': 'bigint NULL',
            'status': 'integer NULL',
            'submit_time': 'bigint NULL',
            'user_id': 'bigint NULL',
            'user_portrait': 'varchar(200) NOT NULL DEFAULT ""',
        }
        
        for field_name, field_type in fields_to_check.items():
            if field_name not in columns:
                try:
                    cursor.execute(f"ALTER TABLE cskh_feedback ADD COLUMN {field_name} {field_type}")
                    print(f"Added column: {field_name}")
                except Exception as e:
                    print(f"Error adding {field_name}: {e}")


def populate_comment_id(apps, schema_editor):
    """Populate comment_id for existing records that have NULL values"""
    Feedback = apps.get_model('cskh', 'Feedback')
    db_alias = schema_editor.connection.alias

    try:
        # Get all feedbacks with NULL comment_id
        feedbacks = Feedback.objects.using(db_alias).filter(comment_id__isnull=True)
    except FieldError:
        # Trường hợp DB mới chưa có cột comment_id trong state model,
        # không cần populate gì vì chưa có dữ liệu lịch sử.
        return

    # Try to populate from feedback_id or cmt_id, otherwise use a generated value
    for feedback in feedbacks:
        if getattr(feedback, "comment_id", None):
            # Đã có comment_id thì bỏ qua
            continue
        if getattr(feedback, "feedback_id", None):
            comment_id = feedback.feedback_id
        elif getattr(feedback, "cmt_id", None):
            comment_id = feedback.cmt_id
        else:
            # Generate a unique negative value (to avoid conflicts with real comment_ids)
            comment_id = -(feedback.id * 1000000 + feedback.id)

        # Make sure it's unique
        while Feedback.objects.using(db_alias).filter(comment_id=comment_id).exists():
            comment_id = comment_id - 1

        feedback.comment_id = comment_id
        feedback.save(using=db_alias)


def reverse_populate_comment_id(apps, schema_editor):
    """Reverse: set comment_id to NULL for records that were auto-populated"""
    # We can't easily reverse this, so just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0014_add_shopee_fields_to_feedback'),
    ]

    operations = [
        # Ensure all columns exist (some may have been added by migration 0014)
        migrations.RunPython(ensure_columns_exist, migrations.RunPython.noop),
        # Populate comment_id for existing NULL values
        migrations.RunPython(populate_comment_id, reverse_populate_comment_id),
        # Now make comment_id non-nullable and unique
        # Update model state for all fields (even if they already exist in DB)
        # This ensures Django's migration state is correct
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations are handled by ensure_columns_exist
            ],
            state_operations=[
                migrations.AddField(
                    model_name='feedback',
                    name='can_follow_up',
                    field=models.BooleanField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='ctime',
                    field=models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='follow_up',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='is_hidden',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='low_rating_reasons',
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='model_id',
                    field=models.BigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='model_name',
                    field=models.CharField(blank=True, max_length=500),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='mtime',
                    field=models.BigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='order_id',
                    field=models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='product_cover',
                    field=models.CharField(blank=True, max_length=200),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='product_id',
                    field=models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='status',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='submit_time',
                    field=models.BigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='user_id',
                    field=models.BigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='user_portrait',
                    field=models.CharField(blank=True, max_length=200),
                ),
                migrations.AlterField(
                    model_name='feedback',
                    name='comment_id',
                    field=models.BigIntegerField(db_index=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='feedback',
                    name='feedback_id',
                    field=models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['comment_id'], name='cskh_feedba_comment_6e0aec_idx'),
        ),
    ]
