# Generated by Django 5.0 on 2025-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0016_trainingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('new', 'Mới'), ('processing', 'Đang xử lý'), ('waiting_customer', 'Chờ khách'), ('waiting_warehouse', 'Chờ kho'), ('waiting_cskh', 'Chờ CSKH xử lý'), ('resolved', 'Đã xử lý'), ('closed', 'Đóng')], default='new', max_length=50),
        ),
    ]
