# Generated by Django 5.0 on 2026-01-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0019_ensure_all_shopee_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='model_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
