# Generated by Django 5.0 on 2026-01-03 14:10

from django.db import migrations, models


def migrate_feedback_id_from_comment_id(apps, schema_editor):
    """
    Copy comment_id sang feedback_id cho các rows có feedback_id = NULL.
    """
    Feedback = apps.get_model('cskh', 'Feedback')
    db_alias = schema_editor.connection.alias
    
    # Copy comment_id sang feedback_id cho các rows có feedback_id = NULL
    feedbacks = Feedback.objects.using(db_alias).filter(feedback_id__isnull=True)
    updated_count = 0
    for feedback in feedbacks:
        if feedback.comment_id:
            feedback.feedback_id = feedback.comment_id
            feedback.save(using=db_alias)
            updated_count += 1
        elif hasattr(feedback, 'cmt_id') and feedback.cmt_id:
            # Fallback: dùng cmt_id nếu không có comment_id
            feedback.feedback_id = feedback.cmt_id
            feedback.save(using=db_alias)
            updated_count += 1
    
    print(f"Updated {updated_count} feedbacks: set feedback_id from comment_id or cmt_id")


def reverse_migrate(apps, schema_editor):
    """Reverse migration - không cần reverse vì đã xóa cmt_id"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0020_increase_feedback_field_lengths'),
    ]

    operations = [
        # Bước 1: Copy comment_id sang feedback_id cho các rows hiện có
        migrations.RunPython(migrate_feedback_id_from_comment_id, reverse_migrate),
        
        # Bước 2: Xóa unique constraint từ comment_id
        migrations.AlterField(
            model_name='feedback',
            name='comment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        
        # Bước 3: Thêm unique constraint cho feedback_id và set NOT NULL
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        
        # Bước 4: Xóa column cmt_id
        migrations.RemoveField(
            model_name='feedback',
            name='cmt_id',
        ),
        
    ]
