# Generated by Django 5.0 on 2026-01-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0021_change_feedback_id_to_primary_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='cskh_feedba_comment_6e0aec_idx',
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['feedback_id'], name='cskh_feedba_feedbac_3f9a47_idx'),
        ),
    ]
