# Generated by Django 5.0 on 2026-01-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0022_remove_feedback_cskh_feedba_comment_6e0aec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync - Sync toàn bộ'), ('incremental', 'Incremental Sync - Cập nhật mới')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('running', 'Đang chạy'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('paused', 'Tạm dừng')], db_index=True, default='pending', max_length=20)),
                ('total_shops', models.IntegerField(default=0)),
                ('current_shop_index', models.IntegerField(default=0)),
                ('current_shop_name', models.CharField(blank=True, max_length=200)),
                ('total_feedbacks', models.IntegerField(default=0)),
                ('processed_feedbacks', models.IntegerField(default=0)),
                ('synced_feedbacks', models.IntegerField(default=0)),
                ('updated_feedbacks', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('shop_progress', models.JSONField(blank=True, default=dict)),
                ('current_connection_id', models.IntegerField(blank=True, null=True)),
                ('current_page', models.IntegerField(default=1)),
                ('current_cursor', models.BigIntegerField(blank=True, null=True)),
                ('last_processed_feedback_id', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('days', models.IntegerField(default=30)),
                ('page_size', models.IntegerField(default=50)),
                ('max_feedbacks_per_shop', models.IntegerField(blank=True, null=True)),
                ('batch_size', models.IntegerField(default=50)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='cskh_feedba_status_85aab5_idx'), models.Index(fields=['sync_type', '-started_at'], name='cskh_feedba_sync_ty_d6a0cd_idx')],
            },
        ),
    ]
