# Generated by Django 5.0 on 2026-01-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0023_feedbacksyncjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksyncjob',
            name='days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
