# Generated by Django 5.0 on 2025-12-01 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0002_ticket_ticketcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePackingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(choices=[('KHO_HCM', 'Kho HCM (Geleximco & Toky)'), ('KHO_HN', 'Kho Hà Nội (Geleximco)')], help_text='Mã kho: KHO_HCM hoặc KHO_HN', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Bật/tắt tính năng đóng gói hàng cho nhân viên thông thường (WarehousePacker)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cài đặt đóng gói hàng kho',
                'verbose_name_plural': 'Cài đặt đóng gói hàng kho',
                'ordering': ['warehouse_code'],
            },
        ),
    ]
