# Generated by Django 5.0 on 2025-12-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_create_variant_sales_forecast'),
    ]

    operations = [
    ]
