# Generated by Django 5.0 on 2025-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_create_variant_sales_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantSalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.BigIntegerField(db_index=True, help_text='Variant ID từ Sapo')),
                ('period_days', models.IntegerField(default=7, help_text='Số ngày tính toán (ví dụ: 7, 14, 30)')),
                ('total_sold', models.IntegerField(default=0, help_text='Tổng lượt bán kỳ hiện tại (x ngày gần nhất)')),
                ('total_sold_previous_period', models.IntegerField(default=0, help_text='Tổng lượt bán kỳ trước (x ngày cùng kỳ)')),
                ('sales_rate', models.FloatField(default=0.0, help_text='Tốc độ bán (số lượng/ngày)')),
                ('growth_percentage', models.FloatField(blank=True, help_text='% tăng trưởng so với kỳ trước', null=True)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='Thời điểm tính toán', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo record')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật cuối')),
            ],
            options={
                'verbose_name': 'Variant Sales Forecast',
                'verbose_name_plural': 'Variant Sales Forecasts',
                'db_table': 'products_variant_sales_forecast',
                'indexes': [models.Index(fields=['variant_id', 'period_days'], name='products_va_variant_ab82b1_idx'), models.Index(fields=['calculated_at'], name='products_va_calcula_3bb26f_idx'), models.Index(fields=['-updated_at'], name='products_va_updated_41d9ce_idx')],
                'unique_together': {('variant_id', 'period_days')},
            },
        ),
    ]
