# Generated by Django 5.0 on 2025-12-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_create_container_and_purchase_order_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containertemplatesupplier',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='containertemplatesupplier',
            name='products_containertemplatesupplier_unique',
        ),
        migrations.RenameIndex(
            model_name='containertemplate',
            new_name='products_co_code_672ff3_idx',
            old_name='products_co_code_idx',
        ),
        migrations.RenameIndex(
            model_name='containertemplate',
            new_name='products_co_is_acti_a046d4_idx',
            old_name='products_co_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='containertemplatesupplier',
            new_name='products_co_contain_5b183a_idx',
            old_name='products_co_contain_idx',
        ),
        migrations.RenameIndex(
            model_name='containertemplatesupplier',
            new_name='products_co_supplie_77b163_idx',
            old_name='products_co_supplie_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='products_pu_sapo_or_030852_idx',
            old_name='products_pu_sapo_or_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='products_pu_sapo_co_af0010_idx',
            old_name='products_pu_sapo_co_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='products_pu_supplie_bfb734_idx',
            old_name='products_pu_supplie_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='products_pu_sum_pur_5dc232_idx',
            old_name='products_pu_sum_pur_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='products_pu_status_722f3c_idx',
            old_name='products_pu_status_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlineitem',
            new_name='products_pu_purchas_003a75_idx',
            old_name='products_pu_purchas_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlineitem',
            new_name='products_pu_sku_b24d94_idx',
            old_name='products_pu_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderlineitem',
            new_name='products_pu_variant_7f4e70_idx',
            old_name='products_pu_variant_idx',
        ),
        migrations.RenameIndex(
            model_name='sumpurchaseorder',
            new_name='products_su_code_a841c5_idx',
            old_name='products_su_code_idx',
        ),
        migrations.RenameIndex(
            model_name='sumpurchaseorder',
            new_name='products_su_status_df0124_idx',
            old_name='products_su_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sumpurchaseorder',
            new_name='products_su_contain_610774_idx',
            old_name='products_su_contain_idx',
        ),
        migrations.RenameIndex(
            model_name='sumpurchaseorder',
            new_name='products_su_created_eb928c_idx',
            old_name='products_su_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='containertemplatesupplier',
            unique_together={('container_template', 'supplier_id')},
        ),
    ]
