# Generated by Django 5.0 on 2025-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_containertemplatesupplier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumpurchaseorder',
            name='destination_port',
            field=models.CharField(blank=True, choices=[('hcm', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng')], help_text='Cảng đến (Hồ Chí Minh hoặc Hải Phòng)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sumpurchaseorder',
            name='expected_arrival_date',
            field=models.DateField(blank=True, help_text='Dự kiến ngày hàng về (phải cách ngày lên đơn tối thiểu 12 ngày)', null=True),
        ),
    ]
