# Generated by Django 5.0 on 2025-12-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_refactor_spo_po_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spopurchaseorder',
            name='products_spo_purchase_order_unique',
        ),
        migrations.RenameIndex(
            model_name='spopurchaseorder',
            new_name='products_sp_sum_pur_00540f_idx',
            old_name='products_sp_sum_pu_sapo_o_idx',
        ),
        migrations.RenameIndex(
            model_name='spopurchaseorder',
            new_name='products_sp_sapo_or_247d6d_idx',
            old_name='products_sp_sapo_or_idx',
        ),
        migrations.AlterUniqueTogether(
            name='spopurchaseorder',
            unique_together={('sum_purchase_order', 'sapo_order_supplier_id')},
        ),
    ]
