# Generated by Django 5.0 on 2025-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_spopurchaseorder_products_spo_purchase_order_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertemplate',
            name='avg_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Giá trị dự kiến của container (để dự trù tài chính)', max_digits=15),
        ),
    ]
