# Generated by Django 5.0 on 2025-12-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_containertemplate_avg_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('created', 'Tạo SPO'), ('sent_to_supplier', 'Gửi đơn NSX'), ('packed', 'Đóng container'), ('departed_cn', 'Tàu rời cảng'), ('arrived_vn', 'Tàu tới HCM/HN'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='draft', max_length=50),
        ),
    ]
