# Generated by Django 5.0 on 2025-12-07 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_spo_po_data(apps, schema_editor):
    """
    Migrate dữ liệu từ SPOPurchaseOrder cũ (với sapo_order_supplier_id) 
    sang PurchaseOrder mới và cập nhật quan hệ.
    """
    db_alias = schema_editor.connection.alias
    PurchaseOrder = apps.get_model('products', 'PurchaseOrder')
    
    # Sử dụng raw SQL để truy cập field sapo_order_supplier_id trực tiếp từ database
    # Vì field này vẫn còn trong database schema tại thời điểm này
    try:
        with schema_editor.connection.cursor() as cursor:
            # Thử SELECT để kiểm tra column có tồn tại không
            try:
                cursor.execute("""
                    SELECT id, sapo_order_supplier_id 
                    FROM products_spo_purchase_order 
                    WHERE sapo_order_supplier_id IS NOT NULL
                """)
                rows = cursor.fetchall()
            except Exception as e:
                # Column không tồn tại hoặc đã bị xóa
                print(f"Warning: Could not access sapo_order_supplier_id column: {e}")
                print("Skipping data migration. This is OK if the column was already removed.")
                return
            
            migrated_count = 0
            for row in rows:
                spo_po_id, sapo_id = row
                
                if not sapo_id:
                    continue
                
                # Tạo hoặc lấy PurchaseOrder
                po, created = PurchaseOrder.objects.using(db_alias).get_or_create(
                    sapo_order_supplier_id=sapo_id,
                    defaults={
                        'supplier_id': 0,  # Sẽ cập nhật sau từ Sapo API
                        'delivery_status': 'ordered',
                        'product_amount_cny': 0,
                        'total_amount_cny': 0,
                        'paid_amount_cny': 0,
                    }
                )
                
                # Cập nhật quan hệ bằng raw SQL
                cursor.execute("""
                    UPDATE products_spo_purchase_order 
                    SET purchase_order_id = %s 
                    WHERE id = %s
                """, [po.id, spo_po_id])
                
                migrated_count += 1
            
            if migrated_count > 0:
                print(f"Migrated {migrated_count} SPOPurchaseOrder records to PurchaseOrder")
            
    except Exception as e:
        print(f"Error during migration: {e}")
        # Nếu có lỗi nghiêm trọng, raise để dừng migration
        raise


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_sumpurchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapo_order_supplier_id', models.BigIntegerField(db_index=True, help_text='Sapo order_supplier.id (unique để đảm bảo mỗi PO chỉ có 1 record)', unique=True)),
                ('sapo_code', models.CharField(blank=True, help_text='Mã PO từ Sapo', max_length=100)),
                ('supplier_id', models.BigIntegerField(db_index=True, help_text='Sapo supplier_id')),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('delivery_status', models.CharField(choices=[('ordered', 'Lên đơn'), ('sent_label', 'Gửi đơn & Label'), ('production', 'Sản xuất'), ('delivered', 'Giao hàng')], default='ordered', help_text='Trạng thái giao hàng của PO', max_length=50)),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Dự kiến giao hàng (để sắp xếp với lịch đóng container)', null=True)),
                ('delivery_timeline', models.JSONField(blank=True, default=list)),
                ('product_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='Tiền hàng (CNY) - tính từ giá mua trung quốc của variants', max_digits=15)),
                ('total_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='Tổng cần thanh toán (CNY) = tiền hàng + chi phí', max_digits=15)),
                ('paid_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền đã thanh toán (CNY) - tự động tính từ payments', max_digits=15)),
                ('note', models.TextField(blank=True, help_text='Ghi chú cho PO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'products_purchase_order',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('domestic_shipping_cn', 'Giao hàng nội địa TQ'), ('packing_fee', 'Phí đóng hàng'), ('other', 'Chi phí khác')], default='other', max_length=50)),
                ('amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cbm', models.DecimalField(blank=True, decimal_places=3, help_text='Mét khối (CBM) để phân bổ chi phí', max_digits=10, null=True)),
                ('description', models.CharField(blank=True, help_text='Mô tả chi phí', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Order Cost',
                'verbose_name_plural': 'Purchase Order Costs',
                'db_table': 'products_purchase_order_cost',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('deposit', 'Cọc sản xuất'), ('payment', 'Thanh toán đơn hàng')], default='payment', max_length=50)),
                ('amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_vnd', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền VNĐ đã bỏ để thanh toán', max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tỷ giá CNY/VNĐ (tự động tính = amount_vnd / amount_cny)', max_digits=10, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Ngày thanh toán')),
                ('description', models.CharField(blank=True, help_text='Mô tả thanh toán', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Order Payment',
                'verbose_name_plural': 'Purchase Order Payments',
                'db_table': 'products_purchase_order_payment',
            },
        ),
        migrations.RemoveIndex(
            model_name='spopurchaseorder',
            name='products_sp_sum_pur_00540f_idx',
        ),
        migrations.RemoveIndex(
            model_name='spopurchaseorder',
            name='products_sp_sapo_or_247d6d_idx',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='spopurchaseorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='spopurchaseorder',
            name='purchase_order',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='spo_relations', to='products.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='spopurchaseorder',
            index=models.Index(fields=['sum_purchase_order', 'purchase_order'], name='products_sp_sum_pur_69cca2_idx'),
        ),
        migrations.AddIndex(
            model_name='spopurchaseorder',
            index=models.Index(fields=['purchase_order'], name='products_sp_purchas_7d325c_idx'),
        ),
        migrations.AddField(
            model_name='purchaseordercost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordercost',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='products.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['sapo_order_supplier_id'], name='products_pu_sapo_or_030852_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier_id'], name='products_pu_supplie_bfb734_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['delivery_status'], name='products_pu_deliver_5a9672_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_delivery_date'], name='products_pu_expecte_69cd22_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-created_at'], name='products_pu_created_f2e241_idx'),
        ),
        migrations.RemoveField(
            model_name='spopurchaseorder',
            name='domestic_shipping_cn',
        ),
        migrations.RemoveField(
            model_name='spopurchaseorder',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='spopurchaseorder',
            name='expected_production_date',
        ),
        # Migrate data: Tạo PurchaseOrder từ SPOPurchaseOrder cũ
        migrations.RunPython(
            code=migrate_spo_po_data,
            reverse_code=migrations.RunPython.noop,
        ),
        # Sau khi migrate xong, set purchase_order thành NOT NULL và thêm unique_together
        migrations.AlterField(
            model_name='spopurchaseorder',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spo_relations', to='products.purchaseorder'),
        ),
        migrations.AlterUniqueTogether(
            name='spopurchaseorder',
            unique_together={('sum_purchase_order', 'purchase_order')},
        ),
        migrations.RemoveField(
            model_name='spopurchaseorder',
            name='sapo_order_supplier_id',
        ),
        migrations.AddIndex(
            model_name='purchaseordercost',
            index=models.Index(fields=['purchase_order'], name='products_pu_purchas_7fc095_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordercost',
            index=models.Index(fields=['cost_type'], name='products_pu_cost_ty_9e1322_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['purchase_order'], name='products_pu_purchas_4e0c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['payment_type'], name='products_pu_payment_bf9b61_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderpayment',
            index=models.Index(fields=['payment_date'], name='products_pu_payment_766b51_idx'),
        ),
    ]
