# Generated by Django 5.0 on 2025-12-07 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_purchaseorder_purchaseordercost_purchaseorderpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPOCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên chi phí (ví dụ: Vận chuyển, Hải quan...)', max_length=200)),
                ('amount_vnd', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền (VNĐ)', max_digits=15)),
                ('note', models.TextField(blank=True, help_text='Ghi chú chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sum_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='products.sumpurchaseorder')),
            ],
            options={
                'verbose_name': 'SPO Cost',
                'verbose_name_plural': 'SPO Costs',
                'db_table': 'products_spo_cost',
                'indexes': [models.Index(fields=['sum_purchase_order'], name='products_sp_sum_pur_a97646_idx')],
            },
        ),
        migrations.CreateModel(
            name='SPODocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File chứng từ', upload_to='spo_documents/%Y/%m/')),
                ('name', models.CharField(blank=True, help_text='Tên tài liệu (nếu để trống sẽ lấy tên file)', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sum_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.sumpurchaseorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SPO Document',
                'verbose_name_plural': 'SPO Documents',
                'db_table': 'products_spo_document',
                'indexes': [models.Index(fields=['sum_purchase_order'], name='products_sp_sum_pur_98f36c_idx')],
            },
        ),
    ]
