# Generated by Django 5.0 on 2025-12-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_spocost_spodocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumpurchaseorder',
            name='created_date',
            field=models.DateField(blank=True, help_text='Ngày tạo SPO (có thể điền thủ công)', null=True),
        ),
    ]
