# Generated by Django 5.0 on 2025-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sumpurchaseorder_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantABCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.BigIntegerField(db_index=True, help_text='Variant ID từ Sapo')),
                ('category', models.CharField(choices=[('A', 'Nhóm A (70-80% doanh thu)'), ('B', 'Nhóm B (15-25% doanh thu)'), ('C', 'Nhóm C (5-10% doanh thu)')], db_index=True, help_text='Phân loại ABC', max_length=1)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Tổng doanh thu (line_amount) trong 30 ngày', max_digits=15)),
                ('quantity_sold', models.IntegerField(default=0, help_text='Tổng số lượng bán ra (quantity) trong 30 ngày')),
                ('average_selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Giá bán trung bình (ASP) = revenue / quantity_sold', max_digits=15)),
                ('revenue_percentage', models.FloatField(default=0.0, help_text='% doanh thu trên tổng doanh thu')),
                ('cumulative_percentage', models.FloatField(default=0.0, help_text='% tích lũy cộng dồn (từ cao xuống thấp)')),
                ('rank', models.IntegerField(db_index=True, default=0, help_text='Thứ tự xếp hạng theo doanh thu (1 = cao nhất)')),
                ('calculated_at', models.DateTimeField(blank=True, help_text='Thời điểm tính toán', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo record')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật cuối')),
            ],
            options={
                'verbose_name': 'Variant ABC Analysis',
                'verbose_name_plural': 'Variant ABC Analyses',
                'db_table': 'products_variant_abc_analysis',
                'indexes': [models.Index(fields=['variant_id'], name='products_va_variant_42edeb_idx'), models.Index(fields=['category'], name='products_va_categor_240522_idx'), models.Index(fields=['rank'], name='products_va_rank_bc3d33_idx'), models.Index(fields=['calculated_at'], name='products_va_calcula_74e055_idx'), models.Index(fields=['-updated_at'], name='products_va_updated_0845c5_idx')],
            },
        ),
    ]
