# Generated by Django 5.0 on 2025-12-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_variantabcanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantABCAnalysis',
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='abc_category',
            field=models.CharField(blank=True, choices=[('A', 'Nhóm A (70-80% doanh thu)'), ('B', 'Nhóm B (15-25% doanh thu)'), ('C', 'Nhóm C (5-10% doanh thu)')], db_index=True, help_text='Phân loại ABC (chỉ có khi period_days=30)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='abc_rank',
            field=models.IntegerField(blank=True, db_index=True, help_text='Thứ tự xếp hạng theo doanh thu (1 = cao nhất, chỉ có khi period_days=30)', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='cumulative_percentage',
            field=models.FloatField(blank=True, help_text='% tích lũy cộng dồn (chỉ có khi period_days=30)', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tổng doanh thu (line_amount) - chỉ tính cho period_days=30', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='revenue_percentage',
            field=models.FloatField(blank=True, help_text='% doanh thu trên tổng doanh thu (chỉ có khi period_days=30)', null=True),
        ),
        migrations.AddIndex(
            model_name='variantsalesforecast',
            index=models.Index(fields=['abc_category'], name='products_va_abc_cat_bcb857_idx'),
        ),
        migrations.AddIndex(
            model_name='variantsalesforecast',
            index=models.Index(fields=['abc_rank'], name='products_va_abc_ran_00fa63_idx'),
        ),
    ]
