# Generated by Django 5.0 on 2025-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_variantabcanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsalesforecast',
            name='asp_score',
            field=models.IntegerField(blank=True, help_text='ASP Score (2, 4, 6, 8, 10) dựa trên phân vị giá trị SKU', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='priority_score',
            field=models.FloatField(blank=True, db_index=True, help_text='Điểm ưu tiên (0-10) = 45% Velocity Stability + 30% ASP + 25% Revenue Contribution', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='revenue_contribution_score',
            field=models.IntegerField(blank=True, help_text='Revenue Contribution Score (4, 7, 10) từ nhóm ABC', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='stability_bonus',
            field=models.IntegerField(blank=True, help_text='Stability Bonus (0, 1, 2) dựa trên so sánh cùng kỳ 7 ngày', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='velocity_score',
            field=models.IntegerField(blank=True, help_text='Velocity Score (2, 4, 6, 8, 10) dựa trên phân vị tốc độ bán', null=True),
        ),
        migrations.AddField(
            model_name='variantsalesforecast',
            name='velocity_stability_score',
            field=models.FloatField(blank=True, help_text='Velocity Stability Score (0-12) = VelocityScore + Stability Bonus', null=True),
        ),
        migrations.AddIndex(
            model_name='variantsalesforecast',
            index=models.Index(fields=['priority_score'], name='products_va_priorit_8b23bb_idx'),
        ),
    ]
