# Generated by Django 5.0 on 2025-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_variantsalesforecast_asp_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumpurchaseorder',
            name='ship_name',
            field=models.CharField(blank=True, help_text='Tên tàu', max_length=200),
        ),
        migrations.AddField(
            model_name='sumpurchaseorder',
            name='ship_tracking_link',
            field=models.URLField(blank=True, help_text='Link tracking vị trí tàu', max_length=500),
        ),
    ]
