# Generated by Django 5.0 on 2025-12-13 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_add_ship_info_to_spo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spocost',
            name='amount_cny',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền (CNY) - nếu thanh toán từ số dư', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit_bank', 'Nạp qua ngân hàng'), ('deposit_black_market', 'Mua chợ đen'), ('withdraw_po', 'Rút - Thanh toán PO'), ('withdraw_spo_cost', 'Rút - Chi phí SPO')], help_text='Loại giao dịch', max_length=50)),
                ('amount_cny', models.DecimalField(decimal_places=2, help_text='Số tiền nhân dân tệ (dương = nạp, âm = rút)', max_digits=15)),
                ('amount_vnd', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền VNĐ đã chi (chỉ có khi nạp)', max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tỷ giá CNY/VNĐ', max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Tên ngân hàng (nếu nạp qua ngân hàng)', max_length=200)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, help_text='Ngày giao dịch')),
                ('description', models.TextField(blank=True, help_text='Mô tả giao dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order_payment', models.ForeignKey(blank=True, help_text='Liên kết với thanh toán PO (nếu là rút)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='products.purchaseorderpayment')),
                ('spo_cost', models.ForeignKey(blank=True, help_text='Liên kết với chi phí SPO (nếu là rút)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='products.spocost')),
            ],
            options={
                'verbose_name': 'Balance Transaction',
                'verbose_name_plural': 'Balance Transactions',
                'db_table': 'products_balance_transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorderpayment',
            name='balance_transaction',
            field=models.OneToOneField(blank=True, help_text='Giao dịch số dư tương ứng (tự động tạo khi thanh toán)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_payment_link', to='products.balancetransaction'),
        ),
        migrations.AddField(
            model_name='spocost',
            name='balance_transaction',
            field=models.OneToOneField(blank=True, help_text='Giao dịch số dư tương ứng (tự động tạo khi thanh toán)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spo_cost_link', to='products.balancetransaction'),
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Mã kỳ thanh toán (ví dụ: KTT2025-001)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Tên kỳ thanh toán (tùy chọn)', max_length=200)),
                ('start_date', models.DateField(help_text='Ngày đầu kỳ')),
                ('end_date', models.DateField(help_text='Ngày cuối kỳ')),
                ('avg_exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tỷ giá trung bình trong kỳ (tự động tính)', max_digits=10, null=True)),
                ('opening_balance_cny', models.DecimalField(decimal_places=2, default=0, help_text='Số dư đầu kỳ (CNY)', max_digits=15)),
                ('closing_balance_cny', models.DecimalField(decimal_places=2, default=0, help_text='Số dư cuối kỳ (CNY) - tự động tính', max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Period',
                'verbose_name_plural': 'Payment Periods',
                'db_table': 'products_payment_period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPeriodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_periods', to='products.balancetransaction')),
                ('payment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_transactions', to='products.paymentperiod')),
            ],
            options={
                'verbose_name': 'Payment Period Transaction',
                'verbose_name_plural': 'Payment Period Transactions',
                'db_table': 'products_payment_period_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['transaction_type'], name='products_ba_transac_48898f_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['transaction_date'], name='products_ba_transac_b5152d_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['-transaction_date'], name='products_ba_transac_3f6f02_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentperiod',
            index=models.Index(fields=['code'], name='products_pa_code_11a624_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='products_pa_start_d_c5fead_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentperiod',
            index=models.Index(fields=['-start_date'], name='products_pa_start_d_955e55_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentperiodtransaction',
            index=models.Index(fields=['payment_period', 'balance_transaction'], name='products_pa_payment_686345_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentperiodtransaction',
            unique_together={('payment_period', 'balance_transaction')},
        ),
    ]
