# Generated by Django 5.0 on 2025-12-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_add_payment_spo_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentperiod',
            name='closing_balance_cny',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED - Số dư cuối kỳ tính realtime, không lưu', max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='opening_balance_cny',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số dư đầu kỳ (CNY) - chỉ dùng cho kỳ đầu tiên', max_digits=15),
        ),
    ]
