# Generated by Django 5.0 on 2025-12-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_paymentperiod_closing_balance_cny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spocost',
            name='cost_side',
            field=models.CharField(choices=[('china', 'Phía Trung Quốc'), ('vietnam', 'Phía Việt Nam')], default='china', help_text='Phía chi phí: Trung Quốc (CNY, trừ từ số dư) hoặc Việt Nam (VND, không trừ từ số dư)', max_length=20),
        ),
    ]
