# Generated by Django 5.0 on 2025-12-15 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_spocost_cost_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='spocost',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Ngày giao dịch (ngày phát sinh chi phí)'),
        ),
    ]
