# Generated by Django 5.0 on 2025-12-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_add_transaction_date_to_spo_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPOPackingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(blank=True, help_text='Mã HS', max_length=50)),
                ('sku_nhapkhau', models.CharField(db_index=True, help_text='SKU nhập khẩu', max_length=100)),
                ('vn_name', models.CharField(blank=True, help_text='Tên tiếng Việt (Mô tả hàng hóa)', max_length=500)),
                ('en_name', models.CharField(blank=True, help_text='Tên tiếng Anh', max_length=500)),
                ('cn_name', models.CharField(blank=True, help_text='Tên tiếng Trung', max_length=500)),
                ('nsx_name', models.CharField(blank=True, help_text='Tên nhà sản xuất', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Số lượng', max_digits=15)),
                ('unit', models.CharField(blank=True, help_text='Đơn vị', max_length=50)),
                ('box', models.DecimalField(decimal_places=3, default=0, help_text='Số thùng', max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Đơn giá hóa đơn (USD)', max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Tổng giá trị (USD)', max_digits=15)),
                ('total_cpm', models.DecimalField(decimal_places=3, default=0, help_text='Tổng CBM', max_digits=15)),
                ('total_weight', models.DecimalField(decimal_places=3, default=0, help_text='Tổng trọng lượng (g)', max_digits=15)),
                ('material', models.CharField(blank=True, help_text='Chất liệu', max_length=500)),
                ('import_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Thuế suất nhập khẩu (%)', max_digits=5)),
                ('import_tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền thuế nhập khẩu', max_digits=15)),
                ('import_tax_total', models.DecimalField(decimal_places=2, default=0, help_text='Tổng số tiền thuế nhập khẩu', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, help_text='Thuế suất GTGT (%)', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Số tiền thuế GTGT', max_digits=15)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, help_text='Tổng số tiền thuế GTGT', max_digits=15)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự sắp xếp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sum_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list_items', to='products.sumpurchaseorder')),
            ],
            options={
                'verbose_name': 'SPO Packing List Item',
                'verbose_name_plural': 'SPO Packing List Items',
                'db_table': 'products_spo_packing_list_item',
                'ordering': ['order', 'sku_nhapkhau'],
                'indexes': [models.Index(fields=['sum_purchase_order'], name='products_sp_sum_pur_f8630e_idx'), models.Index(fields=['sku_nhapkhau'], name='products_sp_sku_nha_a38b15_idx'), models.Index(fields=['sum_purchase_order', 'order'], name='products_sp_sum_pur_fc36de_idx')],
            },
        ),
    ]
