# Generated by Django 5.0 on 2025-12-29 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_add_spo_packing_list_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkhq_code', models.CharField(blank=True, db_index=True, help_text='Mã tờ khai hải quan (nếu có)', max_length=100)),
                ('variant_id', models.BigIntegerField(db_index=True, help_text='Variant ID từ Sapo')),
                ('location_id', models.BigIntegerField(db_index=True, help_text='Location ID (kho hàng) từ Sapo')),
                ('receipt_code', models.CharField(blank=True, help_text='Mã phiếu nhập kho (receipt code) từ Sapo', max_length=100)),
                ('import_date', models.DateField(help_text='Ngày nhập kho')),
                ('import_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Số lượng nhập mới', max_digits=15)),
                ('old_cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Giá vốn cũ (trước khi nhập)', max_digits=15)),
                ('old_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Số lượng tồn kho cũ (trước khi nhập)', max_digits=15)),
                ('new_cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Giá vốn mới (sau khi tính toán)', max_digits=15)),
                ('average_cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Giá vốn trung bình (bình quân gia quyền) = (old_qty * old_price + new_qty * new_price) / (old_qty + new_qty)', max_digits=15)),
                ('price_cny', models.DecimalField(decimal_places=2, default=0, help_text='Giá nhập CNY (từ price_tq trong metadata)', max_digits=15)),
                ('exchange_rate_avg', models.DecimalField(decimal_places=4, default=0, help_text='Tỷ giá CNY trung bình', max_digits=10)),
                ('import_tax_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Thuế nhập khẩu đơn chiếc (VNĐ)', max_digits=15)),
                ('vat_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Thuế GTGT đơn chiếc (VNĐ)', max_digits=15)),
                ('po_cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Chi phí riêng của PO phân bổ trên CPM cho đơn chiếc (VNĐ)', max_digits=15)),
                ('spo_cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Tổng chi phí SPO phân bổ trên CPM cho đơn chiếc (VNĐ)', max_digits=15)),
                ('sku', models.CharField(blank=True, help_text='SKU của variant', max_length=100)),
                ('sku_model_xnk', models.CharField(blank=True, db_index=True, help_text='SKU-MODEL-XNK (nhập khẩu) để match với packing list', max_length=100)),
                ('cpm_per_unit', models.DecimalField(decimal_places=3, default=0, help_text='CBM của 1 chiếc sản phẩm', max_digits=10)),
                ('synced_to_sapo', models.BooleanField(default=False, help_text='Đã đồng bộ lên Sapo price_adjustments chưa')),
                ('sapo_price_adjustment_id', models.BigIntegerField(blank=True, help_text='ID của price_adjustment trên Sapo (nếu đã sync)', null=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='Thời điểm sync lên Sapo', null=True)),
                ('note', models.TextField(blank=True, help_text='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='PO (Purchase Order) - Đơn nhập hàng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_histories', to='products.purchaseorder')),
                ('sum_purchase_order', models.ForeignKey(blank=True, help_text='SPO (Sum Purchase Order) - Đợt nhập container', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_histories', to='products.sumpurchaseorder')),
            ],
            options={
                'verbose_name': 'Cost History',
                'verbose_name_plural': 'Cost Histories',
                'db_table': 'products_cost_history',
                'ordering': ['-import_date', 'variant_id', 'location_id'],
                'indexes': [models.Index(fields=['variant_id', 'location_id'], name='products_co_variant_8b8d7d_idx'), models.Index(fields=['sum_purchase_order'], name='products_co_sum_pur_6e50ba_idx'), models.Index(fields=['purchase_order'], name='products_co_purchas_e90d08_idx'), models.Index(fields=['import_date'], name='products_co_import__36ef69_idx'), models.Index(fields=['sku_model_xnk'], name='products_co_sku_mod_793e9c_idx'), models.Index(fields=['synced_to_sapo'], name='products_co_synced__17dde8_idx'), models.Index(fields=['-created_at'], name='products_co_created_1451d2_idx')],
            },
        ),
    ]
