# Generated by Django 5.0 on 2026-01-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_costhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapoProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(db_index=True, help_text='Sapo product ID', unique=True)),
                ('data', models.JSONField(help_text='JSON data của product từ Sapo API (bao gồm variants)')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Thời điểm sync cuối cùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo record')),
            ],
            options={
                'verbose_name': 'Sapo Product Cache',
                'verbose_name_plural': 'Sapo Product Cache',
                'db_table': 'products_sapo_product_cache',
                'indexes': [models.Index(fields=['product_id'], name='products_sa_product_eb3ffb_idx'), models.Index(fields=['-synced_at'], name='products_sa_synced__05043c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SapoVariantCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.BigIntegerField(db_index=True, help_text='Sapo variant ID', unique=True)),
                ('product_id', models.BigIntegerField(db_index=True, help_text='Sapo product ID (parent)')),
                ('data', models.JSONField(help_text='JSON data của variant từ Sapo API')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Thời điểm sync cuối cùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo record')),
            ],
            options={
                'verbose_name': 'Sapo Variant Cache',
                'verbose_name_plural': 'Sapo Variant Cache',
                'db_table': 'products_sapo_variant_cache',
                'indexes': [models.Index(fields=['variant_id'], name='products_sa_variant_1fac09_idx'), models.Index(fields=['product_id'], name='products_sa_product_2278e2_idx'), models.Index(fields=['-synced_at'], name='products_sa_synced__206b54_idx')],
            },
        ),
    ]
